/** Explicit videos for Prisma seed (problemName + fontGrade + board resolve to problemId). */
export const videos = [
  {
    problemName: "KESBEKE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyYRfS1OrxK/embed",
    video: "https://www.instagram.com/reel/CyYRfS1OrxK/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SEVENTH SEAL",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CybIfVwOIQY/embed",
    video: "https://www.instagram.com/reel/CybIfVwOIQY/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FELICE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyudftzOh4K/embed",
    video: "https://www.instagram.com/reel/CyudftzOh4K/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SPORT4",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cyvb5JoOAPc/embed",
    video: "https://www.instagram.com/reel/Cyvb5JoOAPc/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LAST ORDERS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyyCtonOROB/embed",
    video: "https://www.instagram.com/reel/CyyCtonOROB/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CHICKEN SOUP",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyyEd53uo8B/embed",
    video: "https://www.instagram.com/reel/CyyEd53uo8B/embed",
    uploaded_by: 1,
  },
  {
    problemName: "MOREESPRESSOLESSDEPRESSO",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy1vb_BulLa/embed",
    video: "https://www.instagram.com/reel/Cy1vb_BulLa/embed",
    uploaded_by: 1,
  },
  {
    problemName: "TAG TEAM",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy7NUWmObTf/embed",
    video: "https://www.instagram.com/reel/Cy7NUWmObTf/embed",
    uploaded_by: 1,
  },
  {
    problemName: "GUNS PROJ",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy8RbePOS2i/embed",
    video: "https://www.instagram.com/reel/Cy8RbePOS2i/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SPAKLE BACK LARRY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy9lXuDugwx/embed",
    video: "https://www.instagram.com/reel/Cy9lXuDugwx/embed",
    uploaded_by: 1,
  },
  {
    problemName: "HOME 46",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzAMTAPu2Bc/embed",
    video: "https://www.instagram.com/reel/CzAMTAPu2Bc/embed",
    uploaded_by: 1,
  },
  {
    problemName: "PINCHOCCIO",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyPWDTvOiV7/embed",
    video: "https://www.instagram.com/reel/CyPWDTvOiV7/embed",
    uploaded_by: 1,
  },
  {
    problemName: "POPPED CHERRY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyLbipAuit8/embed",
    video: "https://www.instagram.com/reel/CyLbipAuit8/embed",
    uploaded_by: 1,
  },
  {
    problemName: "VOLVO 480",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyKfkw2uGW7/embed",
    video: "https://www.instagram.com/reel/CyKfkw2uGW7/embed",
    uploaded_by: 1,
  },
  {
    problemName: "KYRA CONNIES",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyUoHsSuuq8/embed",
    video: "https://www.instagram.com/reel/CyUoHsSuuq8/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ANGER THERAPY",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyM4vaAO015/embed",
    video: "https://www.instagram.com/reel/CyM4vaAO015/embed",
    uploaded_by: 1,
  },
  {
    problemName: "AL 11",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy0nxlLOZ8G/embed",
    video: "https://www.instagram.com/reel/Cy0nxlLOZ8G/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ALTITUDE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzMwKhauGCl/embed",
    video: "https://www.instagram.com/reel/CzMwKhauGCl/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DRAMATICALLY WARM",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyUoTD6ua9f/embed",
    video: "https://www.instagram.com/reel/CyUoTD6ua9f/embed",
    uploaded_by: 1,
  },
  {
    problemName: "PIZZA GREASER",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwTB7jUIkwk/embed",
    video: "https://www.instagram.com/reel/CwTB7jUIkwk/embed",
    uploaded_by: 1,
  },
  {
    problemName: "STROLL",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy7MfKbuyqs/embed",
    video: "https://www.instagram.com/reel/Cy7MfKbuyqs/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FOR A RAINY DAY",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwis8cwo4A1/embed",
    video: "https://www.instagram.com/reel/Cwis8cwo4A1/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SAWDUST LAKSA",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwTouaQIJEq/embed",
    video: "https://www.instagram.com/reel/CwTouaQIJEq/embed",
    uploaded_by: 1,
  },
  {
    problemName: "THINKPOL",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyO9B-sOOTX/embed",
    video: "https://www.instagram.com/reel/CyO9B-sOOTX/embed",
    uploaded_by: 1,
  },
  {
    problemName: "NUGGET PRESSURE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyXJShoO6Um/embed",
    video: "https://www.instagram.com/reel/CyXJShoO6Um/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CAL FREE ALT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwnncM3I6jf/embed",
    video: "https://www.instagram.com/reel/CwnncM3I6jf/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FURRY FANDANGO",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyPdLKKOTXF/embed",
    video: "https://www.instagram.com/reel/CyPdLKKOTXF/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BEDTIME",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyYNmuzOLDQ/embed",
    video: "https://www.instagram.com/reel/CyYNmuzOLDQ/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ELOQUENCE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyLpKuLOAyo/embed",
    video: "https://www.instagram.com/reel/CyLpKuLOAyo/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DA REAL 6A+",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyBw_ViuNHP/embed",
    video: "https://www.instagram.com/reel/CyBw_ViuNHP/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BIG MILEAGE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd7nPtoFsd/embed",
    video: "https://www.instagram.com/reel/Cwd7nPtoFsd/embed",
    uploaded_by: 1,
  },
  {
    problemName: "PSYCHONAUT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy_HHgiOD99/embed",
    video: "https://www.instagram.com/reel/Cy_HHgiOD99/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CHICKEN LOCKS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyS1k_ZO45Z/embed",
    video: "https://www.instagram.com/reel/CyS1k_ZO45Z/embed",
    uploaded_by: 1,
  },
  {
    problemName: "VOLCANIC VALOR",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwp6_Z8ueYA/embed",
    video: "https://www.instagram.com/reel/Cwp6_Z8ueYA/embed",
    uploaded_by: 1,
  },
  {
    problemName: "MOKA POT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzTlhuSuv8S/embed",
    video: "https://www.instagram.com/reel/CzTlhuSuv8S/embed",
    uploaded_by: 1,
  },
  {
    problemName: "IVORY ANKLE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwnny1bocQm/embed",
    video: "https://www.instagram.com/reel/Cwnny1bocQm/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LOOK UP LOCK DOWN",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwldb2tIveL/embed",
    video: "https://www.instagram.com/reel/Cwldb2tIveL/embed",
    uploaded_by: 1,
  },
  {
    problemName: "GERALT OF RIVIA",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwjYyvFIJlQ/embed",
    video: "https://www.instagram.com/reel/CwjYyvFIJlQ/embed",
    uploaded_by: 1,
  },
  {
    problemName: "MOONBOARD BLUES",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy3Qv7oupby/embed",
    video: "https://www.instagram.com/reel/Cy3Qv7oupby/embed",
    uploaded_by: 1,
  },
  {
    problemName: "STINGER",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzRhIN9uunV/embed",
    video: "https://www.instagram.com/reel/CzRhIN9uunV/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SWALLOW",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzVIKOLMveg/embed",
    video: "https://www.instagram.com/reel/CzVIKOLMveg/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ARCHIBUSE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd-v5yoyeJ/embed",
    video: "https://www.instagram.com/reel/Cwd-v5yoyeJ/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DESIGN IN MALICE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzKrt1uOJZn/embed",
    video: "https://www.instagram.com/reel/CzKrt1uOJZn/embed",
    uploaded_by: 1,
  },
  {
    problemName: "THE HAND THAT BLEEDS",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzC5bCOuLTa/embed",
    video: "https://www.instagram.com/reel/CzC5bCOuLTa/embed",
    uploaded_by: 1,
  },
  {
    problemName: "YOU GOT MY MONEY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzOYauwuwtZ/embed",
    video: "https://www.instagram.com/reel/CzOYauwuwtZ/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LE DIAGANOL",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyYu-tduKBn/embed",
    video: "https://www.instagram.com/reel/CyYu-tduKBn/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BORN ON TUESDAY NIGHT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzR6f1xu1Hm/embed",
    video: "https://www.instagram.com/reel/CzR6f1xu1Hm/embed",
    uploaded_by: 1,
  },
  {
    problemName: "WEDNESDAY",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0WjSmMuZ5P/embed",
    video: "https://www.instagram.com/reel/C0WjSmMuZ5P/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LICHTBLICK",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cv_hnhgrISc/embed",
    video: "https://www.instagram.com/reel/Cv_hnhgrISc/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LE MOUSTIQUE",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyBxMTpuXy1/embed",
    video: "https://www.instagram.com/reel/CyBxMTpuXy1/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LE RÊVE DE LIVIO",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cx-uqvnOSn8/embed",
    video: "https://www.instagram.com/reel/Cx-uqvnOSn8/embed",
    uploaded_by: 1,
  },
  {
    problemName: "WINGS LIKE A BIRD",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyCDQonuGC_/embed",
    video: "https://www.instagram.com/reel/CyCDQonuGC_/embed",
    uploaded_by: 1,
  },
  {
    problemName: "NEON KNIGHTS",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C5fLbmNu2me/embed",
    video: "https://www.instagram.com/reel/C5fLbmNu2me/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FLUFFY BEER",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C3BxQd3u0cs/embed",
    video: "https://www.instagram.com/reel/C3BxQd3u0cs/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SOUNDS OF THE DEEP",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C3Bw0wYubWV/embed",
    video: "https://www.instagram.com/reel/C3Bw0wYubWV/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SPEAK OF THE DEVIL",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C2i5lMEOhOr/embed",
    video: "https://www.instagram.com/reel/C2i5lMEOhOr/embed",
    uploaded_by: 1,
  },
  {
    problemName: "REACĆION EN CADENA",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C2gxT9GuBSN/embed",
    video: "https://www.instagram.com/reel/C2gxT9GuBSN/embed",
    uploaded_by: 1,
  },
  {
    problemName: "NOMAD HEART",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C2gxDE6uT_C/embed",
    video: "https://www.instagram.com/reel/C2gxDE6uT_C/embed",
    uploaded_by: 1,
  },
  {
    problemName: "NANOMAN",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0JpRNguPHg/embed",
    video: "https://www.instagram.com/reel/C0JpRNguPHg/embed",
    uploaded_by: 1,
  },
  {
    problemName: "POOR HAMSTRING",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0Jn8nlugdt/embed",
    video: "https://www.instagram.com/reel/C0Jn8nlugdt/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SURPRISE SURPRISE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cz3pSzWuLCt/embed",
    video: "https://www.instagram.com/reel/Cz3pSzWuLCt/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SLUGS ON PARADE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cz2CjwTuGcN/embed",
    video: "https://www.instagram.com/reel/Cz2CjwTuGcN/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FROWNS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzX_9jSuHRU/embed",
    video: "https://www.instagram.com/reel/CzX_9jSuHRU/embed",
    uploaded_by: 1,
  },
  {
    problemName: "RELAXATION TONIC",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzF1Xt1OVIu/embed",
    video: "https://www.instagram.com/reel/CzF1Xt1OVIu/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SHADOW GAO'S PARTY",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyuLLJRuZQQ/embed",
    video: "https://www.instagram.com/reel/CyuLLJRuZQQ/embed",
    uploaded_by: 1,
  },
  {
    problemName: "HITHERTO",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyuZozxOeTa/embed",
    video: "https://www.instagram.com/reel/CyuZozxOeTa/embed",
    uploaded_by: 1,
  },
  {
    problemName: "NAILS WITH 1 LEG",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy3QwfWum1f/embed",
    video: "https://www.instagram.com/reel/Cy3QwfWum1f/embed",
    uploaded_by: 1,
  },
  {
    problemName: "KRISS CROSS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Czw95jFO9gW/embed",
    video: "https://www.instagram.com/reel/Czw95jFO9gW/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SORRY I MISSED THE SECOND",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy2OZbmuVbt/embed",
    video: "https://www.instagram.com/reel/Cy2OZbmuVbt/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LEMON ZESTY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy4mQXwussn/embed",
    video: "https://www.instagram.com/reel/Cy4mQXwussn/embed",
    uploaded_by: 1,
  },
  {
    problemName: "GIN TAMA",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy2OMuYOXv5/embed",
    video: "https://www.instagram.com/reel/Cy2OMuYOXv5/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SLAUGHTERHOUSE",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/p/Cwl4gVio7bP/embed",
    video: "https://www.instagram.com/p/Cwl4gVio7bP/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FIRST KOALA",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd8LNAILNP/embed",
    video: "https://www.instagram.com/reel/Cwd8LNAILNP/embed",
    uploaded_by: 1,
  },
  {
    problemName: "B MOONS REANIMATED CORPSE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cy8Q86quTWo/embed",
    video: "https://www.instagram.com/reel/Cy8Q86quTWo/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BRUNO BLOC",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C1apPgyODjC/embed",
    video: "https://www.instagram.com/reel/C1apPgyODjC/embed",
    uploaded_by: 1,
  },
  {
    problemName: "JAMES ISN'T HERE",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C6bkkUbxapP/embed",
    video: "https://www.instagram.com/reel/C6bkkUbxapP/embed",
    uploaded_by: 1,
  },
  {
    problemName: "GRIP IT N RIP IT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyMe0wWu9Js/embed",
    video: "https://www.instagram.com/reel/CyMe0wWu9Js/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DAYSHIFT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyL09CVudb2/embed",
    video: "https://www.instagram.com/reel/CyL09CVudb2/embed",
    uploaded_by: 1,
  },
  {
    problemName: "OVER EASY",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyUpAJuumcH/embed",
    video: "https://www.instagram.com/reel/CyUpAJuumcH/embed",
    uploaded_by: 1,
  },
  {
    problemName: "PUGS IN A BLANKET",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyByxetOFgE/embed",
    video: "https://www.instagram.com/reel/CyByxetOFgE/embed",
    uploaded_by: 1,
  },
  {
    problemName: "TREEBEARD",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CweALV1ortR/embed",
    video: "https://www.instagram.com/reel/CweALV1ortR/embed",
    uploaded_by: 1,
  },
  {
    problemName: "THE COMMODORE",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cvnha5aPGYG/embed",
    video: "https://www.instagram.com/reel/Cvnha5aPGYG/embed",
    uploaded_by: 1,
  },
  {
    problemName: "STYX",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CvnpJVFMTps/embed",
    video: "https://www.instagram.com/reel/CvnpJVFMTps/embed",
    uploaded_by: 1,
  },
  {
    problemName: "OVER THE HILL",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cv_gf1nN2Ut/embed",
    video: "https://www.instagram.com/reel/Cv_gf1nN2Ut/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ADIOS A.MEGOS",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwBCMzcoPnH/embed",
    video: "https://www.instagram.com/reel/CwBCMzcoPnH/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BLACK MUFFLER",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwS-cYAoi3W/embed",
    video: "https://www.instagram.com/reel/CwS-cYAoi3W/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BRIGHTFIELD",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwS_hb6ISVT/embed",
    video: "https://www.instagram.com/reel/CwS_hb6ISVT/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DEVILMAN",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwTDv0WIcyC/embed",
    video: "https://www.instagram.com/reel/CwTDv0WIcyC/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ACG32",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwTo_nZota9/embed",
    video: "https://www.instagram.com/reel/CwTo_nZota9/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ON FIRE ???",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwTpT5hIsjV/embed",
    video: "https://www.instagram.com/reel/CwTpT5hIsjV/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LUKA MESEC",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwTp6J9oQt3/embed",
    video: "https://www.instagram.com/reel/CwTp6J9oQt3/embed",
    uploaded_by: 1,
  },
  {
    problemName: "MIDNIGHT DANCE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd7IS0omI3/embed",
    video: "https://www.instagram.com/reel/Cwd7IS0omI3/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CROSSING JORDAN",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd9DP1IhMh/embed",
    video: "https://www.instagram.com/reel/Cwd9DP1IhMh/embed",
    uploaded_by: 1,
  },
  {
    problemName: "TOEFOOL",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd9iSrohTg/embed",
    video: "https://www.instagram.com/reel/Cwd9iSrohTg/embed",
    uploaded_by: 1,
  },
  {
    problemName: "STINKFIST",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd-ONnINe6/embed",
    video: "https://www.instagram.com/reel/Cwd-ONnINe6/embed",
    uploaded_by: 1,
  },
  {
    problemName: "HULTQVIST'S NO 18",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwd_3UYIQUH/embed",
    video: "https://www.instagram.com/reel/Cwd_3UYIQUH/embed",
    uploaded_by: 1,
  },
  {
    problemName: "HVIT MÅNED",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CweAcYVIwjf/embed",
    video: "https://www.instagram.com/reel/CweAcYVIwjf/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CRIMP NO MORE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CweAufzI5sd/embed",
    video: "https://www.instagram.com/reel/CweAufzI5sd/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LONELY YELLOW",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwesMaxIQvF/embed",
    video: "https://www.instagram.com/reel/CwesMaxIQvF/embed",
    uploaded_by: 1,
  },
  {
    problemName: "MOON RIDER",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyveTIwOQ8v/embed",
    video: "https://www.instagram.com/reel/CyveTIwOQ8v/embed",
    uploaded_by: 1,
  },
  {
    problemName: "PLUTO'S REVENGE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwlMvbwo7ft/embed",
    video: "https://www.instagram.com/reel/CwlMvbwo7ft/embed",
    uploaded_by: 1,
  },
  {
    problemName: "RED FLAGS",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwlNqCaIXU8/embed",
    video: "https://www.instagram.com/reel/CwlNqCaIXU8/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BUG SPRAY",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwldHiZoj-m/embed",
    video: "https://www.instagram.com/reel/CwldHiZoj-m/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DROP IT LIKE IT'S HOT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CwnnN4EIlOV/embed",
    video: "https://www.instagram.com/reel/CwnnN4EIlOV/embed",
    uploaded_by: 1,
  },
  {
    problemName: "STORMFRONT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyyDX6yOdmb/embed",
    video: "https://www.instagram.com/reel/CyyDX6yOdmb/embed",
    uploaded_by: 1,
  },
  {
    problemName: "YAYA WOOD",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwp6rPiuDOS/embed",
    video: "https://www.instagram.com/reel/Cwp6rPiuDOS/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ORCA",
    fontGrade: "7A",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwp73czORsJ/embed",
    video: "https://www.instagram.com/reel/Cwp73czORsJ/embed",
    uploaded_by: 1,
  },
  {
    problemName: "MENSCHINE",
    fontGrade: "7A",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cwp8vylO67q/embed",
    video: "https://www.instagram.com/reel/Cwp8vylO67q/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FLOWERS FOR DAYZ",
    fontGrade: "7A",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cx-vFJmutZw/embed",
    video: "https://www.instagram.com/reel/Cx-vFJmutZw/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BLACK MIRROR",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyyoSg0OECh/embed",
    video: "https://www.instagram.com/reel/CyyoSg0OECh/embed",
    uploaded_by: 1,
  },
  {
    problemName: "NO DREAM IS JUST A DREAM",
    fontGrade: "7A",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Cx-vteHu9D1/embed",
    video: "https://www.instagram.com/reel/Cx-vteHu9D1/embed",
    uploaded_by: 1,
  },
  {
    problemName: "FOUNDATION'S EDGE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyKZYmXOdp2/embed",
    video: "https://www.instagram.com/reel/CyKZYmXOdp2/embed",
    uploaded_by: 1,
  },
  {
    problemName: "THE SCENT OF THE SHORE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyKaYjJu5T3/embed",
    video: "https://www.instagram.com/reel/CyKaYjJu5T3/embed",
    uploaded_by: 1,
  },
  {
    problemName: "REAL BEGINNERS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyLo-3sulAO/embed",
    video: "https://www.instagram.com/reel/CyLo-3sulAO/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BEFORE THE SUN DIES",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyzzdTvOmb5/embed",
    video: "https://www.instagram.com/reel/CyzzdTvOmb5/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CARIBOU",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyOifc3u4M9/embed",
    video: "https://www.instagram.com/reel/CyOifc3u4M9/embed",
    uploaded_by: 1,
  },
  {
    problemName: "WARM_6",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzPRKs8uwhw/embed",
    video: "https://www.instagram.com/reel/CzPRKs8uwhw/embed",
    uploaded_by: 1,
  },
  {
    problemName: "TOLERABLE AQI",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CzRGu1-ORNw/embed",
    video: "https://www.instagram.com/reel/CzRGu1-ORNw/embed",
    uploaded_by: 1,
  },
  {
    problemName: "CHEESECAKE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyQeyvpOS7Y/embed",
    video: "https://www.instagram.com/reel/CyQeyvpOS7Y/embed",
    uploaded_by: 1,
  },
  {
    problemName: "VENGEANCE, BADGE & A GUN",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/Czu6TTQuXZr/embed",
    video: "https://www.instagram.com/reel/Czu6TTQuXZr/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SHOULD HAVE KNOW BETTER",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyXJDPIOnfe/embed",
    video: "https://www.instagram.com/reel/CyXJDPIOnfe/embed",
    uploaded_by: 1,
  },
  {
    problemName: "T REX",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0LJKTzOZnh/embed",
    video: "https://www.instagram.com/reel/C0LJKTzOZnh/embed",
    uploaded_by: 1,
  },
  {
    problemName: "HEKYLAND",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0RbhVCO1hj/embed",
    video: "https://www.instagram.com/reel/C0RbhVCO1hj/embed",
    uploaded_by: 1,
  },
  {
    problemName: "SNOOZE BOTTLE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/CyXJxd-ux2t/embed",
    video: "https://www.instagram.com/reel/CyXJxd-ux2t/embed",
    uploaded_by: 1,
  },
  {
    problemName: "BACK TO THE MOON",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0bt1IBuZMP/embed",
    video: "https://www.instagram.com/reel/C0bt1IBuZMP/embed",
    uploaded_by: 1,
  },
  {
    problemName: "LIL' PINK DINK",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C0mFgbTuwDF/embed",
    video: "https://www.instagram.com/reel/C0mFgbTuwDF/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DARK SHINE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C01aRD5OzY7/embed",
    video: "https://www.instagram.com/reel/C01aRD5OzY7/embed",
    uploaded_by: 1,
  },
  {
    problemName: "ACG34",
    fontGrade: "6C",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C1P1LlMOZhf/embed",
    video: "https://www.instagram.com/reel/C1P1LlMOZhf/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DOUBLE BUBBLE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C4tY2C8u4wm/embed",
    video: "https://www.instagram.com/reel/C4tY2C8u4wm/embed",
    uploaded_by: 1,
  },
  {
    problemName: "DIMENSIONALITY REDUCTION",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    link: "https://www.instagram.com/reel/C5fL7gQuDFX/embed",
    video: "https://www.instagram.com/reel/C5fL7gQuDFX/embed",
    uploaded_by: 1,
  },
];

/** Explicit list of unique problems (Prisma Problem shape: name, vGrade, fontGrade, board). */
export const problems = [
  { name: "KESBEKE", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "SEVENTH SEAL",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "FELICE", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  { name: "SPORT4", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "LAST ORDERS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "CHICKEN SOUP",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "MOREESPRESSOLESSDEPRESSO",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "TAG TEAM", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "GUNS PROJ",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "SPAKLE BACK LARRY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "HOME 46", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "PINCHOCCIO",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "POPPED CHERRY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "VOLVO 480",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "KYRA CONNIES",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "ANGER THERAPY",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "AL 11", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  { name: "ALTITUDE", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "DRAMATICALLY WARM",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "PIZZA GREASER",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "STROLL", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "FOR A RAINY DAY",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "SAWDUST LAKSA",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "THINKPOL", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "NUGGET PRESSURE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "CAL FREE ALT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "FURRY FANDANGO",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "BEDTIME", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "ELOQUENCE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "DA REAL 6A+",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "BIG MILEAGE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "PSYCHONAUT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "CHICKEN LOCKS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "VOLCANIC VALOR",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "MOKA POT", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "IVORY ANKLE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "LOOK UP LOCK DOWN",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "GERALT OF RIVIA",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    vGrade: "V5",
  },
  {
    name: "MOONBOARD BLUES",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "STINGER", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  { name: "SWALLOW", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "ARCHIBUSE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "DESIGN IN MALICE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "THE HAND THAT BLEEDS",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "YOU GOT MY MONEY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "LE DIAGANOL",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "BORN ON TUESDAY NIGHT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "WEDNESDAY",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "LICHTBLICK",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    vGrade: "V5",
  },
  {
    name: "LE MOUSTIQUE",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    vGrade: "V5",
  },
  {
    name: "LE RÊVE DE LIVIO",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    vGrade: "V5",
  },
  {
    name: "WINGS LIKE A BIRD",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    vGrade: "V5",
  },
  {
    name: "NEON KNIGHTS",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "FLUFFY BEER",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "SOUNDS OF THE DEEP",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "SPEAK OF THE DEVIL",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "REACĆION EN CADENA",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "NOMAD HEART",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "NANOMAN", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "POOR HAMSTRING",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "SURPRISE SURPRISE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "SLUGS ON PARADE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "FROWNS", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "RELAXATION TONIC",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "SHADOW GAO'S PARTY",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "HITHERTO", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "NAILS WITH 1 LEG",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "KRISS CROSS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "SORRY I MISSED THE SECOND",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "LEMON ZESTY",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "GIN TAMA", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "SLAUGHTERHOUSE",
    fontGrade: "7A+",
    board: "Moonboard_2019",
    vGrade: "V5",
  },
  {
    name: "FIRST KOALA",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "B MOONS REANIMATED CORPSE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "BRUNO BLOC",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "JAMES ISN'T HERE",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "GRIP IT N RIP IT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "DAYSHIFT", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  { name: "OVER EASY", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "PUGS IN A BLANKET",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "TREEBEARD",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "THE COMMODORE",
    fontGrade: "6C",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "STYX", fontGrade: "6C+", board: "Moonboard_2019", vGrade: "V3" },
  {
    name: "OVER THE HILL",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "ADIOS A.MEGOS",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "BLACK MUFFLER",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "BRIGHTFIELD",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "DEVILMAN", fontGrade: "6C+", board: "Moonboard_2019", vGrade: "V3" },
  { name: "ACG32", fontGrade: "6C+", board: "Moonboard_2019", vGrade: "V3" },
  {
    name: "ON FIRE ???",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "LUKA MESEC",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "MIDNIGHT DANCE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "CROSSING JORDAN",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "TOEFOOL", fontGrade: "6C+", board: "Moonboard_2019", vGrade: "V3" },
  {
    name: "STINKFIST",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "HULTQVIST'S NO 18",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "HVIT MÅNED",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "CRIMP NO MORE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "LONELY YELLOW",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "MOON RIDER",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "PLUTO'S REVENGE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "RED FLAGS",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "BUG SPRAY",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "DROP IT LIKE IT'S HOT",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "STORMFRONT",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "YAYA WOOD",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "ORCA", fontGrade: "7A", board: "Moonboard_2019", vGrade: "V4" },
  { name: "MENSCHINE", fontGrade: "7A", board: "Moonboard_2019", vGrade: "V4" },
  {
    name: "FLOWERS FOR DAYZ",
    fontGrade: "7A",
    board: "Moonboard_2019",
    vGrade: "V4",
  },
  {
    name: "BLACK MIRROR",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "NO DREAM IS JUST A DREAM",
    fontGrade: "7A",
    board: "Moonboard_2019",
    vGrade: "V4",
  },
  {
    name: "FOUNDATION'S EDGE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "THE SCENT OF THE SHORE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "REAL BEGINNERS",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "BEFORE THE SUN DIES",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "CARIBOU", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  { name: "WARM_6", fontGrade: "6B", board: "Moonboard_2019", vGrade: "V2" },
  {
    name: "TOLERABLE AQI",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "CHEESECAKE",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "VENGEANCE, BADGE & A GUN",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "SHOULD HAVE KNOW BETTER",
    fontGrade: "6B+",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  { name: "T REX", fontGrade: "6B+", board: "Moonboard_2019", vGrade: "V2" },
  { name: "HEKYLAND", fontGrade: "6C+", board: "Moonboard_2019", vGrade: "V3" },
  {
    name: "SNOOZE BOTTLE",
    fontGrade: "6B",
    board: "Moonboard_2019",
    vGrade: "V2",
  },
  {
    name: "BACK TO THE MOON",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "LIL' PINK DINK",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "DARK SHINE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  { name: "ACG34", fontGrade: "6C", board: "Moonboard_2019", vGrade: "V3" },
  {
    name: "DOUBLE BUBBLE",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
  {
    name: "DIMENSIONALITY REDUCTION",
    fontGrade: "6C+",
    board: "Moonboard_2019",
    vGrade: "V3",
  },
];
